# Generated by Django 6.0.2 on 2026-05-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_achievement_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
